<?php

/**
 * Danish Language Pack for FerieSystem
 * Simple and clear Danish translations for non-technical users
 * 'superuser' is translated as 'underviser' (instructor/teacher)
 */

return [
    // Application name
    'app_name' => 'FerieSystem',
    
    // General UI
    'welcome' => 'Velkommen',
    'dashboard' => 'Oversigt',
    'login' => 'Log ind',
    'logout' => 'Log ud',
    'register' => 'Opret konto',
    'create_account' => 'Opret konto',
    'sign_in' => 'Log ind',
    'submit' => 'Send',
    'continue' => 'Fortsæt',
    'back' => 'Tilbage',
    'cancel' => 'Annuller',
    'save' => 'Gem',
    'edit' => 'Rediger',
    'delete' => 'Slet',
    'view' => 'Se',
    'details' => 'Detaljer',
    'close' => 'Luk',
    'yes' => 'Ja',
    'no' => 'Nej',
    'ok' => 'OK',
    'search' => 'Søg',
    'filter' => 'Filtrér',
    'all' => 'Alle',
    'none' => 'Ingen',
    'loading' => 'Indlæser...',
    'please_wait' => 'Vent venligst...',
    
    // Roles
    'student' => 'Studerende',
    'superuser' => 'Underviser',
    'instructor' => 'Underviser',
    'teacher' => 'Underviser',
    
    // Authentication
    'auth_title' => 'FerieSystem Log ind',
    'registration_title' => 'FerieSystem Registrering',
    'create_superuser_title' => 'Opret underviser-konto',
    'user_label' => 'Bruger',
    'username' => 'Brugernavn',
    'email' => 'E-mail',
    'password' => 'Adgangskode',
    'confirm_password' => 'Bekræft adgangskode',
    'name' => 'Navn',
    'full_name' => 'Fulde navn',
    'remember_me' => 'Husk mig',
    'forgot_password' => 'Glemt adgangskode?',
    'no_account' => 'Har du ikke en konto?',
    'register_here' => 'Registrer dig her',
    'back_to_login' => '← Tilbage til log ind',
    'construction_in_progress' => 'Under udvikling 🚧',
    
    // Registration key
    'registration_key' => 'Registreringsnøgle',
    'registration_key_description' => 'Indtast din registreringsnøgle for at fortsætte',
    'registration_key_placeholder' => 'Indtast 8-cifret nøgle',
    'no_key_generated' => 'Ingen nøgle oprettet',
    'generate_new_key' => 'Opret ny nøgle',
    
    // Form placeholders
    'email_placeholder' => 'E-mail eller brugernavn',
    'password_placeholder' => 'Adgangskode',
    'create_password_placeholder' => 'Opret adgangskode',
    'confirm_password_placeholder' => 'Bekræft adgangskode',
    'username_placeholder' => 'Vælg et brugernavn',
    'full_name_placeholder' => 'Fulde navn',
    'search_requests_placeholder' => 'Søg i ansøgninger...',
    'search_students_placeholder' => 'Søg studerende...',
    
    // Form descriptions
    'login_description' => 'Log ind på din konto',
    'registration_description' => 'Udfyld dine oplysninger for at registrere dig',
    'create_superuser_description' => 'Udfyld dine oplysninger for at oprette underviser-konto',
    
    // Navigation
    'new_request' => 'Ny ansøgning',
    'my_requests' => 'Mine ansøgninger',
    'requests' => 'Ansøgninger',
    'students' => 'Studerende',
    'calendar' => 'Kalender',
    'students_management' => 'Håndter studerende',
    'requests_management' => 'Håndter ansøgninger',
    
    // Dashboard
    'welcome_back' => 'Velkommen tilbage',
    'manage_vacation_requests' => 'håndter dine ferieansøgninger',
    'vacation_balance' => 'Feriesaldo',
    'click_for_details' => '(Klik for detaljer)',
    'recent_requests' => 'Seneste ansøgninger',
    'view_all' => 'Se alle',
    'no_recent_requests' => 'Ingen seneste ansøgninger',
    'quick_actions' => 'Hurtige handlinger',
    'hours' => 'timer',
    
    // Vacation requests
    'vacation_request' => 'Ferieansøgning',
    'submit_new_request' => 'Send ny ferieansøgning',
    'select_vacation_period' => 'Vælg ferieperiode',
    'start_date' => 'Startdato',
    'start_date_time' => 'Startdato og tid',
    'end_date' => 'Slutdato',
    'end_date_time' => 'Slutdato og tid',
    'reason' => 'Begrundelse',
    'days' => 'Dage',
    'duration' => 'Varighed',
    'status' => 'Status',
    'select_dates' => 'Vælg datoer',
    'please_select_dates' => 'Vælg venligst datoer',
    'request_reason_placeholder' => 'Beskriv årsagen til din ferieansøgning...',
    
    // Request statuses
    'pending' => 'Afventer',
    'approved' => 'Godkendt',
    'rejected' => 'Afvist',
    'denied' => 'Afvist',
    'cancelled' => 'Annulleret',
    'active' => 'Aktiv',
    'completed' => 'Afsluttet',
    
    // Actions
    'approve' => 'Godkend',
    'deny' => 'Afvis',
    'reject' => 'Afvis',
    'view_details' => 'Se detaljer',
    'edit_request' => 'Rediger ansøgning',
    'cancel_request' => 'Annuller ansøgning',
    
    // Messages and notifications
    'success' => 'Succés',
    'error' => 'Fejl',
    'warning' => 'Advarsel',
    'info' => 'Information',
    'request_submitted_successfully' => 'Ansøgning sendt med succes!',
    'request_approved' => 'Ansøgning godkendt',
    'request_denied' => 'Ansøgning afvist',
    'copied_to_clipboard' => 'Kopieret til udklipsholder',
    'calendar_uploaded_successfully' => 'Kalender uploadet med succes',
    'file_uploaded_successfully' => 'Fil uploadet med succes',
    
    // Error messages
    'please_fill_all_fields' => 'Udfyld venligst alle felter',
    'please_enter_valid_email' => 'Indtast venligst en gyldig e-mailadresse',
    'please_enter_valid_key' => 'Indtast venligst en gyldig 8-cifret registreringsnøgle',
    'please_enter_complete_key' => 'Indtast venligst en komplet 8-cifret registreringsnøgle',
    'please_enter_email_password' => 'Indtast venligst både e-mail og adgangskode',
    'please_fill_required_fields' => 'Udfyld venligst alle påkrævede felter korrekt',
    'please_select_start_end_dates' => 'Vælg venligst start- og slutdato for at forhåndsvise',
    'please_select_pdf_file' => 'Vælg venligst en PDF-fil først',
    'please_enter_valid_hours' => 'Indtast venligst et gyldigt antal timer',
    'please_provide_reason' => 'Angiv venligst en begrundelse for justeringen',
    'login_failed_try_again' => 'Log ind mislykkedes. Prøv igen',
    'registration_failed_try_again' => 'Registrering mislykkedes. Prøv igen',
    'key_verification_error' => 'Der opstod en fejl under verifikation af nøglen. Prøv igen',
    'network_error' => 'Netværks- eller serverfejl',
    'internal_server_error' => 'Intern serverfejl',
    'user_not_authenticated' => 'Bruger ikke logget ind',
    'invalid_input_data' => 'Ugyldige inputdata',
    'missing_required_fields' => 'Manglende påkrævede felter',
    'only_pdf_files_allowed' => 'Kun PDF-filer er tilladt',
    'file_size_too_large' => 'Filstørrelse kan ikke overstige 10MB',
    'upload_error' => 'Uploadfejl opstod',
    'save_file_failed' => 'Kunne ikke gemme uploadet fil',
    'unexpected_error' => 'En uventet fejl opstod',
    'access_denied' => 'Adgang nægtet',
    'only_superusers_can_upload' => 'Kun undervisere kan uploade kalenderfiler',
    
    // Validation messages
    'select_valid_start_date' => 'Vælg venligst en gyldig startdato',
    'select_valid_end_date' => 'Vælg venligst en gyldig slutdato',
    'end_date_must_be_after_start' => 'Slutdato skal være efter startdato',
    'advance_notice_required' => 'Der kræves forudgående varsel (mindst 48 timer)',
    'short_notice_warning' => '(Kort varsel - kan tage længere tid at godkende)',
    'low_balance_warning' => 'Dit feriesaldo er lavt',
    
    // Search and filtering
    'no_results_found' => 'Ingen resultater fundet',
    'no_requests_found' => 'Ingen ansøgninger fundet',
    'no_students_found' => 'Ingen studerende fundet',
    'try_adjusting_search' => 'Prøv at justere dine søgekriterier',
    'no_pending_requests' => 'Ingen ventende ansøgninger',
    'all_requests_processed' => 'Alle ansøgninger er blevet behandlet',
    
    // File operations
    'upload' => 'Upload',
    'download' => 'Download',
    'file' => 'Fil',
    'calendar_file' => 'Kalenderfil',
    'pdf_file' => 'PDF-fil',
    
    // Calendar translations
    'calendar' => 'Kalender',
    'calendar_upload_description' => 'Denne side giver undervisere mulighed for at uploade en PDF-version af kalenderen, så studerende kan planlægge deres ansøgninger i overensstemmelse hermed',
    'upload_calendar_pdf' => 'Upload kalender PDF',
    'upload_latest_calendar' => 'Upload den seneste version af kalenderen i PDF-format',
    'calendar_preview' => 'Kalendervisning',
    'no_calendar_uploaded' => 'Ingen kalender PDF uploadet',
    'upload_pdf_to_preview' => 'Upload en PDF for at se forhåndsvisning her',
    'select_pdf_first' => 'Vælg venligst en PDF-fil først',
    'only_pdf_supported' => 'Kun PDF-filer understøttes',
    'uploading_calendar' => 'Uploader kalender...',
    'calendar_uploaded_successfully' => 'Kalender uploadet med succes',
    'upload_failed' => 'Upload mislykkedes',
    'removing_calendar' => 'Fjerner kalender...',
    'calendar_removed' => 'Kalenderen er blevet fjernet',
    'failed_to_remove_calendar' => 'Kunne ikke fjerne kalender',
    'calendar_loaded' => 'Kalender indlæst (uploadet: %s)',
    'could_not_check_calendar' => 'Kunne ikke kontrollere eksisterende kalender: %s',
    
    // API and error messages  
    'internal_server_error' => 'Intern serverfejl',
    'user_not_authenticated' => 'Bruger ikke autentificeret',
    'only_students_access_dashboard' => 'Kun studerende kan få adgang til dashboard-data',
    'only_students_access_balance' => 'Kun studerende kan få adgang til saldodata',
    'database_connection_failed' => 'Databaseforbindelse mislykkedes',
    'invalid_action_add_subtract' => 'Ugyldig handling. Skal være "tilføj" eller "træk fra"',
    'hours_must_be_positive' => 'Timer skal være et positivt tal',
    'user_not_authenticated' => 'Bruger ikke autentificeret',
    'invalid_input_data' => 'Ugyldige inputdata',
    'missing_required_fields' => 'Manglende påkrævede felter',
    'request_submitted_successfully' => 'Ansøgning indsendt med succes',
    'request_approved_successfully' => 'Ansøgning godkendt med succes',
    'error_approving_request' => 'Fejl ved godkendelse af ansøgning',
    'request_denied_successfully' => 'Ansøgning afvist med succes',
    'only_superusers_deny_requests' => 'Kun undervisere kan afvise ansøgninger',
    'only_superusers_access_data' => 'Kun undervisere kan få adgang til disse data',
    'request_id_required' => 'Ansøgnings-ID er påkrævet',
    'only_superusers_upload_calendar' => 'Kun undervisere kan uploade kalenderfiler',
    'no_file_uploaded' => 'Ingen fil uploadet eller uploadfejl opstod',
    'only_pdf_files_allowed' => 'Kun PDF-filer er tilladt',
    'file_size_limit_10mb' => 'Filstørrelse kan ikke overstige 10MB',
    'failed_to_save_file' => 'Kunne ikke gemme uploadet fil',
    'unexpected_error_occurred' => 'En uventet fejl opstod',
    'only_superusers_adjust_hours' => 'Kun undervisere kan justere timer',
    'only_superusers_delete_calendar' => 'Kun undervisere kan slette kalenderfiler',
    'calendar_deleted_successfully' => 'Kalender slettet med succes',
    'calendar_file_not_found' => 'Kalenderfil ikke fundet',
    'calendar_file_not_found_simple' => 'Kalenderfil ikke fundet',
    'api_endpoint_not_found' => 'API-endpoint ikke fundet',
    'user_id_not_available' => 'Bruger-ID ikke tilgængeligt',
    'user_id_required' => 'Bruger-ID er påkrævet',
    'invalid_json_input' => 'Ugyldigt JSON-input',
    'missing_required_fields_ff' => 'Manglende påkrævede felter: student_id, action, hours, reason',
    'only_superusers_adjust_ff' => 'Kun undervisere kan justere ferie-timer',
    
    // Help text
    'contact_instructor' => 'Kontakt din underviser hvis du har spørgsmål',
    'having_problems' => 'Har du problemer?',
    'ask_instructor' => 'Spørg din underviser',
    'need_help' => 'Har du brug for hjælp?',
    
    // Footer
    'all_rights_reserved' => 'Alle rettigheder forbeholdes',
    'developed_by' => 'Udviklet af',
    
    // Misc
    'profile' => 'Profil',
    'settings' => 'Indstillinger',
    'notifications' => 'Notifikationer',
    'help' => 'Hjælp',
    'about' => 'Om',
    'version' => 'Version',
    'checking_auth_status' => 'Kontrollerer godkendelsesstatus...',
    'page_not_found' => 'Siden blev ikke fundet',
    'go_back' => 'Gå tilbage',
    'home' => 'Hjem',
    
    // Additional translations for remaining content
    'create_super_user_button' => 'Opret underviser',
    'email_address' => 'E-mailadresse',
    'username_field' => 'Brugernavn',
    'my_vacation_requests' => 'Mine ferieansøgninger',
    'track_status_requests' => 'Følg status på dine ferieansøgninger',
    'all_requests' => 'Alle ansøgninger',
    'no_requests_found_message' => 'Ingen ansøgninger fundet',
    'request_summary' => 'Ansøgningsoversigt',
    'balance_after_request' => 'Saldo efter ansøgning',
    'low_balance_notice' => 'Lavt saldo: Denne ansøgning vil efterlade dig med mindre end 3 dages ferie',
    'insufficient_balance_notice' => 'Utilstrækkelig saldo: Denne ansøgning overstiger dine tilgængelige ferietimer',
    'reason_for_request' => 'Begrundelse for ansøgning',
    'be_specific_help' => 'Vær specifik omkring din ansøgning for at sikre hurtig godkendelse',
    'submit_request' => 'Send ansøgning',
    'important_notes' => 'Vigtige noter',
    'submit_48_hours_advance' => 'Send ansøgninger mindst 48 timer i forvejen',
    'emergency_requests_contact' => 'Ved nødsituationer kontakt din underviser',
    'approved_requests_cannot_modify' => 'Godkendte ansøgninger kan ikke ændres',
    'check_balance_before_submit' => 'Tjek din saldo før du sender ansøgning',
    'approved_requests_section' => 'Godkendte ansøgninger',
    'show_label' => 'Vis',
    'active_button' => 'Aktive',
    'completed_button' => 'Afsluttede',
    'view_manage_approved' => 'Se og håndter godkendte ferieansøgninger',
    'passwords_do_not_match' => 'Adgangskoderne matcher ikke!',
    'password_min_length' => 'Adgangskode skal være mindst 8 tegn lang!',
    'view_track_requests' => 'Se og følg dine ferieansøgninger',
    'view_calendar_for_planning' => 'Se kalenderen for at planlægge dine ferieansøgninger',
    'ask_teacher_for_calendar' => 'Spørg din underviser om kalenderen ikke er uploadet endnu',
    
    // Student modal translations
    'student_information' => 'Studerendeoplysninger',
    'contact_information' => 'Kontaktoplysninger',
    'ff_hours_management' => 'Ferie-timer administration',
    'current_ff_balance' => 'Nuværende ferie-saldo',
    'enter_hours' => 'Indtast timer',
    'add_hours' => 'Tilføj timer',
    'remove_hours' => 'Fjern timer',
    'quick_actions' => 'Hurtige handlinger',
    'view_requests' => 'Se ansøgninger',
    'send_message' => 'Send besked',
    'view_history' => 'Se historik',
    'close' => 'Luk',
    'active' => 'Aktiv',
    'error_loading_balance' => 'Fejl ved indlæsning af saldo',
    'failed_to_load' => 'Kunne ikke indlæses',
    'loading' => 'Indlæser...',
    'hours' => 'timer',
    'no_students_found' => 'Ingen studerende fundet',
    'no_students_match_criteria' => 'Ingen studerende matcher dine søgekriterier',
    'error_loading_students' => 'Fejl ved indlæsning af studerende data',
    'failed_to_load_students' => 'Kunne ikke indlæse studerende data',
    'student_data_not_available' => 'Studerendedata ikke tilgængelig',
    'successfully_added' => 'Succesfuldt tilføjet',
    'successfully_removed' => 'Succesfuldt fjernet',
    'failed_to_add' => 'Kunne ikke tilføje',
    'failed_to_remove' => 'Kunne ikke fjerne',
    'error_adding' => 'Fejl ved tilføjelse',
    'error_removing' => 'Fejl ved fjernelse',
    'message_functionality_not_implemented' => 'Beskedfunktionalitet ikke implementeret endnu',
    'loading_transaction_history' => 'Indlæser transaktionshistorik...',
    'could_not_load_transaction_history' => 'Kunne ikke indlæse transaktionshistorik',
    'error_loading_transaction_history' => 'Fejl ved indlæsning af transaktionshistorik',
    
    // FF Hours modal translations
    'adjust_ff_hours' => 'Juster ferie-timer',
    'modify_ff_hours_question' => 'Er du sikker på, at du vil ændre ferie-timer for denne studerende?',
    'reason' => 'Årsag',
    'enter_reason_adjustment' => 'Indtast årsag til justering...',
    'yes_adjust_it' => 'Ja, juster dem!',
    'cancel' => 'Annuller',
    
    // Preview and modal translations
    'request_details' => 'Ansøgningsdetaljer',
    'preview_mode' => 'Forhåndsvisningstilstand',
    'modify_form_preview_again' => 'Dette viser dine ansøgningsdetaljer. Du kan ændre formularen og forhåndsvise igen',
    'close_preview' => 'Luk forhåndsvisning',
    
    // Duration and calculation messages
    'end_must_be_after_start' => 'Slut skal være efter start',
    'error_calculating_duration' => 'Fejl ved beregning af varighed',
    
    // Modal titles
    'request_preview' => 'Ansøgningsforhåndsvisning',
    'profile_information' => 'Profiloplysninger',
    
    // Additional information labels
    'balance_information_unavailable' => 'Saldooplysninger ikke tilgængelige',
    'student_information_header' => 'Studerendeoplysninger',
    'account_information' => 'Kontooplysninger',
    
    // Dashboard modal translations
    'vacation_balance_and_history' => 'Feriesaldo og historik',
    'usage_history' => 'Forbrugshistorik',
    'total_allocated' => 'I alt tildelt',
    'total_used' => 'I alt brugt',
    'pending_requests' => 'Ventende ansøgninger',
    'current_available_balance' => 'Nuværende tilgængelig saldo',
    'transaction_history' => 'Transaktionshistorik',
    'balance_information' => 'Saldooplysninger',
    'annual_allocation' => 'Årlig tildeling',
    'annual_allocation_text' => 'Du tildeles 200 ferietimer pr. akademisk år',
    'current_period' => 'Nuværende periode',
    'current_academic_year' => 'September 2024 - Juni 2025',
    'rollover_policy' => 'Overførselspolitik',
    'rollover_policy_text' => 'Ubrugte timer overføres ikke til næste akademiske år',
    'hour_calculation' => 'Timeberegning',
    'hour_calculation_text' => '8 timer = 1 arbejdsdag. Weekendtimer spores separat',
    'no_transactions_found' => 'Ingen transaktioner fundet',
];
